import {
    RepairDatePipe,
    KeysPipe,
    SearchKeyPipe,
    GetLabelPipe,
    PicNumberPipe,
    RmbPipe,
    FormatSrcPipe,
    DistancePipe,
    DetailPipe,
    LabelPipe,
    HtmlPipe,
    ChipsPipe,
    UserStatusPipe,
    ProjectStatusPipe,
    TableLabelPipe,
    ColorPipe,
    ScorePipe,
    ProgressPipe,
    IndustryNamePipe
} from './pipes.pipe';

export const PIPES_DECLARATIONS = [
    RepairDatePipe,
    KeysPipe,
    SearchKeyPipe,
    GetLabelPipe,
    PicNumberPipe,
    RmbPipe,
    FormatSrcPipe,
    DistancePipe,
    DetailPipe,
    LabelPipe,
    HtmlPipe,
    ChipsPipe,
    UserStatusPipe,
    ProjectStatusPipe,
    TableLabelPipe,
    ColorPipe,
    ScorePipe,
    ProgressPipe,
    IndustryNamePipe
];
